secrets: secretfile.yml
templates:
  global:
    domain_delay:
      www.torrentleech.org: 10 seconds
      rss.torrentleech.org: 10 minutes
      bt-chat.com: 5 seconds
      torrentz.eu: 5 seconds
    if:
      - "'torrentleech' in url":
          deluge:
            ratio: 3.0
            removeatratio: yes
            port: 58846
            main_file_only: yes
      - "'torrentleech' not in url":
          deluge:
            ratio: 1.0
            removeatratio: yes
            port: 58846
            main_file_only: yes
    free_space:
      path: /mnt/disk1/
      space: 10000
    regexp:
      reject:
        - (s|d)ub(s|bed)?\b: {from: title} 
        - (duo|tri|quadri|tetra|penta|hexa|hepta|octa|ennea|deca)logy 
        - \b3-?D\b: {from: title}          
        - \bR5\b: {from: title}            
        - \bWEBSCR\b: {from: title}        
        - \bscreener\b: {from: title}
        - \bTS\b: {from: title}
        - \bCam\b: {from: title} 
        - "{C_P}": {from: title}
        - \bFRENCH\b: {from: title}
        - \bSPANiSH\b: {from: title}
        - \btrailer\b: {from: title}
        - "SCR": {from: title}
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.m4v'
        - '*.mp4'
        - '*.rar'
      reject:
        - '*.m2ts'
        - 'password.txt'
        - '*.wmv'
    pathscrub: windows
    retry_failed:
      retry_time: 1 hour
      retry_time_multiplier: 2
      max_retries: 5
    verify_ssl_certificates: no
    magnets: no
      
  tv-global:
    inputs:
      - rss: { url: '{{ secrets.tl.url }}', silent: yes }
    content_size:
      max: 8000
      min: 20
    exists_series:
      - "/mnt/disk1/Library/TvShows/"
      - "/home/bsmith/Downloads/staging/TvShows"
    #thetvdb_lookup: yes
    trakt_lookup: yes
    set:
      content_filename: "{{ series_name|replace('/', '_')|replace(':', ' ') }} - {{ trakt_ep_id|default(series_id) }}{% if trakt_ep_name|default(False) %} - {{ trakt_ep_name|replace('/', '_')|replace(':', ' -') }}{% endif %} - {{ quality }}"
      movedone: "/mnt/disk1/Library/TvShows/{{ series_name|replace('/', '_')|replace(':', ' ') }}/{% if series_id_type == 'ep' %}Season {{ trakt_season|default(series_season) }}/{% endif %}"
    content_sort:
      '*.rar': "/home/bsmith/Downloads/completed/TvShows/"
    pushbullet:
      apikey: '{{ secrets.pushb.apikey }}'
      device: '{{ secrets.pushb.device }}'
      title: "[Flexget] {{series_name}} {{series_id}}"
      body: "{{task}} - {% if trakt_series_url is defined %}{{trakt_series_url}}/season/{{trakt_season}}/episode/{{trakt_episode}}{% endif %}"

  movie-global:
    inputs:
      - rss: { url: '{{ secrets.tl.url }}', silent: yes }
      #- rss: { url: 'http://kickass.to/movies/genre/news/?rss=1', silent: yes }
    if:
      - "has_field('category')":
          regexp:
            reject_excluding:
              - '^(HD|BDRip|DVDRip.DVDScreener|DVD-R|Documentaries)$': {from: category}
    archive: [movies]
    content_size:
      max: 15000
      min: 1000
    exists_movie:
      - "/mnt/disk1/Library/Movies/"
      - "/home/bsmith/Downloads/staging/Movies/"
    tmdb_lookup: yes
    imdb_lookup: yes
    trakt_lookup: yes
    set:
      content_filename: "{{ tmdb_name|replace('/', '_')|replace(':', ' ') }} ({{ tmdb_year }}) - {{ quality }}"
      movedone: "/mnt/disk1/Library/Movies/{{ tmdb_name|replace('/', '_')|replace(':', ' ') }} ({{ tmdb_year }})"
    content_sort:
      '*.rar': "/home/bsmith/Downloads/completed/Movies/"
    pushbullet:
      apikey: '{{ secrets.pushb.apikey }}'
      device: '{{ secrets.pushb.device }}'
      title: "[Flexget] Movie Downloaded"
      body: "{{task}} - {{ imdb_name }} {{ imdb_year }} - {{ quality }}"

  movies-discover:
    discover:
      from:
        - torrentleech:
            rss_key: '{{ secrets.tl.rss }}'
            username: '{{ secrets.tl.user_name }}'
            password: '{{ secrets.tl.password }}'
            category: ['HD', 'BDRip', 'DVDRip', 'DVDR', 'Documentaries']
        - flexget_archive: [movies]
        - kat:
            category: movies
            verified: yes
        #- torrentz:
        #    reputation: verified
        #    extra_terms: "movie* hd"
        #- piratebay:
        #    category: "highres movies"
        #    sort_by: seeds
      what: [filler: yes]

  movies-queued:
    movie_queue: accept
    template: movies-discover
    disable:
      - seen_movies
    discover:
      what:
        - emit_movie_queue: yes
      from: 
        - filler: yes
    set:
      label: my-movies
    trakt_remove:
      username: '{{ secrets.trakt_info.user_name }}'
      password: '{{ secrets.trakt_info.password }}'
      list: Movie_Queue
    trakt_add:
      username: '{{ secrets.trakt_info.user_name }}'
      password: '{{ secrets.trakt_info.password }}'
      list: watchlist

tasks:
  tv-my-shows:
    priority: 5
    include: [ series-tvshows.yml ]
    template:
      - tv-global
    set:
      label: tv-my-shows
    configure_series:
      from:
        trakt_list:
          username: '{{ secrets.trakt_info.user_name }}'
          password: '{{ secrets.trakt_info.password }}'
          list: TvShows   
          type: shows
      settings:
        target: 720p+ dvdscr+
        timeframe: 1 days
        quality: 480p+ webrip+

  tv-interesting:
    priority: 6
    include: [ series-interesting.yml ] 
    template:
      - tv-global
    set:
      label: tv-interesting
    configure_series:
      from:
        trakt_list:
          username: '{{ secrets.trakt_info.user_name }}'
          password: '{{ secrets.trakt_info.password }}'
          list: Interesting
          type: shows
      settings:
        target: 720p+ dvdscr+
        timeframe: 3 days
        quality: 480p+ webrip+

  tv-reality:
    priority: 7
    include: [ series-reality.yml ]
    template:
      - tv-global
    set:
      label: tv-reality
    configure_series:
      from:
        trakt_list:
          username: '{{ secrets.trakt_info.user_name }}'
          password: '{{ secrets.trakt_info.password }}'
          list: RealityTV   
          type: shows
      settings:
        target: hdtv+ dvdscr+
        timeframe: 3 days
        quality: 480p+ webrip+             

  tv-laura:
    priority: 8
    #include: [ series-wife.yml ]
    template:
      - tv-global
    set:
      label: tv-laura
    configure_series:
      from:
        trakt_list:
          username: '{{ secrets.trakt_info.user_name }}'
          password: '{{ secrets.trakt_info.password }}'
          list: Laura   
          type: shows
      settings:
        target: 720p+ dvdscr+
        timeframe: 2 days
        quality: 480p+ webrip+             
              
  clean-movie-queue:
    priority: 90
    template: no_global
    disable:
      - seen
      - seen_info_hash
      - seen_movies
    accept_all: yes
    listdir:
      - /mnt/disk1/Library/Movies/
    imdb_lookup: yes
    trakt_lookup: yes
    tmdb_lookup: yes
    require_field: [movie_name, movie_year]
    movie_queue: accept
    trakt_remove:
      username: '{{ secrets.trakt_info.user_name }}'
      password: '{{ secrets.trakt_info.password }}'
      list: Movie_Queue

  movies-1080p:
    priority: 110
    template: 
      - movie-global
      - movies-queued
    quality: 1080p+ bluray+ h264+ !mp3 !aac

  movies-720p:
    priority: 120
    template: 
      - movie-global
      - movies-queued
    torrent_alive:
      min_seeds: 5
    quality: 720p+ bluray+ h264+ !mp3 !aac
    delay: 7 days

  imdb-list-to-trakt:
    priority: 1
    template: no_global
    #interval: 2 hours
    imdb_list:
      user_id: ur34962140
      list: watchlist
    trakt_add:
      username: '{{ secrets.trakt_info.user_name }}'
      password: '{{ secrets.trakt_info.password }}'
      list: Movie_Queue
    accept_all: yes
    movie_queue: add

  trakt-list-to-movie-queue:
    priority: 2
    template: no_global
    trakt_list:
      username: '{{ secrets.trakt_info.user_name }}'
      password: '{{ secrets.trakt_info.password }}'
      list: Movie_Queue
      type: movies
    accept_all: yes
    movie_queue: add
  
  google-music-sync:
    priority: 1
    disable: [seen, seen_info_hash]
    template: 
      - no_global # None of the global templates make sense here
     #- music-global
    find:
      path: '/home/bsmith/Dropbox/Music/to_sync/'
      regexp: '.*\.(mp3|flac|m4a|ogg)$'
      recursive: yes
    accept_all: yes
    exec:
      on_output:
        for_accepted: '"/home/bsmith/repos/gmusicapi-scripts/gmsync.py" -q -l -m "{{location}}" && rm "{{location}}"'

  local-torrents-movie:
    priority: 200
    template:
      - movie-global
    disable:
      - seen
      - seen_info_hash
      - configure_series
      - inputs
      - exists_movie
      - seen_movies
      - regexp
      - content_size
      - torrent_alive
      - quality
    # To avoid warnings about non-functional input
    filler: yes 
    # Mark movies as seen
    movie_queue: accept
    plugin_priority:
      exec: 0
    find:
      path: '/home/bsmith/Dropbox/torrents/Movies/'
      regexp: '.*\.torrent$'
      recursive: yes
    exec:
      on_output:
        for_accepted: rm "{{location}}"
    accept_all: yes
    set:
      label: local-movies
    trakt_remove:
      username: '{{ secrets.trakt_info.user_name }}'
      password: '{{ secrets.trakt_info.password }}'
      list: Movie_Queue
    trakt_add:
      username: '{{ secrets.trakt_info.user_name }}'
      password: '{{ secrets.trakt_info.password }}'
      list: watchlist

  local-torrents-tv:
    priority: 201
    include:
      - series-interesting.yml  
      - series-reality.yml  
      - series-tvshows.yml  
     #- series-wife.yml
    template:
      - tv-global
    disable:
      - seen
      - seen_info_hash
      - configure_series
      - trakt_list
      - inputs
      - exists_series
      - regexp
      - content_size
      - torrent_alive
    filler: yes # To avoid warnings about non-functional input
    all_series:
      parse_only: yes
    plugin_priority:
      exec: 0
    find:
      path: '/home/bsmith/Dropbox/torrents/TvShows/'
      regexp: '.*\.torrent$'
      recursive: yes
    exec:
      on_output:
        for_accepted: rm "{{location}}"
    accept_all: yes
    set:
      label: local-tv

  trakt-fall-shows:
    priority: 6
    include: [ series-fall-shows.yml ]
    template: 
      - tv-global
    set:
      label: tv-fall-shows
    configure_series:
      from:
        trakt_list:
          username: '{{ secrets.trakt_info.user_name }}'
          password: '{{ secrets.trakt_info.password }}'
          list: Fall Shows 
          type: shows
      settings:
        timeframe: 2 hours
        target: 720p+ 
        quality: hdtv+ 
        propers: 2 hours

  trakt-moms-shows:
    priority: 6
    include: [ series-moms-shows.yml ]
    template: 
      - tv-global
    set:
      label: tv-mom
    configure_series:
      from:
        trakt_list:
          username: '{{ secrets.trakt_info.user_name }}'
          password: '{{ secrets.trakt_info.password }}'
          list: Moms Shows
          type: shows
      settings:
        timeframe: 2 hours
        target: hdtv+ 
        quality: hdtv+ 
        propers: 2 hours
  
  trakt-daily-shows:
    priority: 2
    include: [ series-daily-shows.yml ]
    template:
      - tv-global
    set:
      label: tv-daily
    configure_series:
      from:
        trakt_list:
          username: '{{ secrets.trakt_info.user_name }}'
          password: '{{ secrets.trakt_info.password }}'
          list: Daily
          type: shows
      settings:
        target: webrip+
        timeframe: 12 hours
        quality: hdtv
        tracking: backfill

#schedules:            
#  - tasks: [ 'tv-my-shows', 'tv-interesting', 'tv-reality', 'tv-laura', 'trakt-fall-shows','movies-1080p', 'movies-720p' ]
#    schedule:
#      minute: 3,18,33,48
#  - tasks: [ 'movies-1080p', 'movies-720p' ]
#    schedule:
#      minute: 30
#  - tasks: [ 'local-torrents-movie', 'google-music-sync', 'local-torrents-tv' ]  
#    schedule:
#      minute: 15
#  - tasks: [ 'trakt-list-to-movie-queue', 'imdb-list-to-trakt' ]
#    schedule:
#      hour: 2

